### ISSUE TITLE
Use `generated always as identity` instead of bigserial?

### ISSUE THREAD

**Issue by craigpastro** [tembo-io/pgmq#100]
Here, and in other places, `bigserial` is used:
https://github.com/tembo-io/pgmq/blob/f8ae3e807c5bace58aff7da723fe3bd536aa28db/core/src/query.rs#L41

However, I think it is recommended to use `generated always as identity` over serial. See https://wiki.postgresql.org/wiki/Don't_Do_This#Don.27t_use_serial for some reasons why.

**Comment by ChuckHend** [comment]
@craigpastro , I we might be able to use `generated as identity` without impact to metrics. We still get an auto incrementing sequence created.

```text
pgmq=# create table test (msg_id BIGINT GENERATED ALWAYS AS IDENTITY, name text);
CREATE TABLE
pgmq=# select * from test_msg_id_seq;
 last_value | log_cnt | is_called 
------------+---------+-----------
          1 |       0 | f
```

```text
pgmq=# insert into test (name) values ('craig');
INSERT 0 1
pgmq=# select * from test_msg_id_seq;
 last_value | log_cnt | is_called 
------------+---------+-----------
          1 |      32 | t
(1 row)
```

**Comment by ChuckHend** [comment]
@ddorian - how would you feel about expanding on the queue types that can be created in order to support client-generated message IDs? For example, we have pgmq.create(), pgmq.create_unlogged(), pgmq.create_partitioned()....we could add pgmq.create() with a flag for client-generated IDs, or a pgmq.create_manual_assigned() or something that makes sense.

**Comment by ddorian** [comment]
I'm sorry but I don't have free time ATM.
