### ISSUE TITLE
[question] why duplicated sqls between core/src/query.rs and src/sql_src.sql

### ISSUE THREAD

**Issue by mrl5** [tembo-io/pgmq#209]
Hello!

First of all great project. It got me really interested so I started checking the code for the sake of curiosity. There are three things that I'm unable to understand and I'd appreciate if someone could clarify.

1. Why some SQL statements are duplicated? Let's take those DMLs for example:
  * [src/sql_src.sql#L37](https://github.com/tembo-io/pgmq/blob/19f9a6fbe63364690cc74580c51d09c4c9beb9c3/src/sql_src.sql#L37) vs [core/src/query.rs#L176](https://github.com/tembo-io/pgmq/blob/19f9a6fbe63364690cc74580c51d09c4c9beb9c3/core/src/query.rs#L176) - there is even slight difference between them in `RETURNING` statement:
```diff
- RETURNING m.msg_id, m.read_ct, m.enqueued_at, m.vt, m.message
+ RETURNING *;
```

To my uderstanding using pgrx should be enough ([`pg_extern`](https://docs.rs/pgrx/latest/pgrx/attr.pg_extern.html) probably handles that)? So why there's a need for such duplication?

2. On the other hand some are defined only in one place, e.g.  [`read_with_poll`](https://github.com/tembo-io/pgmq/blob/19f9a6fbe63364690cc74580c51d09c4c9beb9c3/src/sql_src.sql#L73C22-L73C36) (that I could find only in `src/sql_src.sql`)

Now I assume that it's somehow related to this line https://github.com/tembo-io/pgmq/blob/19f9a6fbe63364690cc74580c51d09c4c9beb9c3/src/lib.rs#L8 but still I failed with reverse engineering that.

3. To my understanding `pgmq-rs` allows both pure rust client issuing raw sql statements (not UDFs) as well as rust sdk that requires pgmq extension installed in postgres cluster. If I'm correct then it additionally makes sense to have the same DML defined once and referenced in multiple places - contrary to the example that I described in `#1`

I'd appreciate some friendly soul trying to answer above questions :)

**Comment by ChuckHend** [comment]
Hello @mrl5! Thank you for taking a look!

Short Answer: there is really no need for the duplication. With some refactors, I think all/most the DML and DDL could be defined once and shared across client libs and the extension.

Longer answer:

**Regarding 1 and 3**: There is definitely opportunity for a more elegant solution in how both the DML and DDL are managed. The code duplication is just an artifact of how the project has evolved and not really a design decision or anything like that.

Some history -- the project originally started as a client-side only Rust project (in pgmq-rs), and then moved to an extension when we wanted to make it accessible to non-Rust projects, and `pgrx` was the smoothest way to do that. It can be difficult to compile `pgrx`, so the Rust code shared between client the the extension were moved to ./core, with the Rust client living in ./pgmq-rs. That lets users install the Rust client, without compiling pgrx, and did reduce some duplication at the time.

Theres [some interest](https://github.com/tembo-io/pgmq/issues/199) in refactoring parts from Rust to pl/pgsql which will make the project more portable. That work is partially complete (everything in ./sql_src.sql used to be in Rust at one point in time), resulting in some of the code duplication that you are seeing.

**Regarding 2**: read_with_poll() is only available by installing the extension (not in the Rust client-only lib). Thats why its only defined one place. It's not duplicated, because it was implemented after the transition from a client-only project to an extension project

Hopefully this helps. Nice work reverse engineering 😄 . We're very open to refactors, and if you are interested in helping out we could pair up on it.

**Comment by mrl5** [comment]
thanks for both comprehensive answer - it makes sense now ...
... and for contribution invite :100: !

keep up the great work you're doing!
