### ISSUE TITLE
pg_dump failed with Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by elvizlai** [tembo-io/pgmq#371]
create extension pgmq;
SELECT pgmq.create('test_topic');

then using pg_dump to dump specified database, it failed with:
```
Segmentation fault (core dumped)
```

using param `--exclude-schema='pgmq'` works!

**Comment by ChuckHend** [comment]
@elvizlai there was a bug fixed in https://github.com/tembo-io/pgmq/pull/352 that should resolve this issue. It is on `main` now and will be out with v1.5.0 soon.

`ALTER EXTENSION pgmq ADD SEQUENCE pgmq.q_<your_queue_name>_msg_id_seq` should also resolve the seg fault. Could you try this and let us know if it resolves the issue for you?

**Comment by elvizlai** [comment]
> ALTER EXTENSION pgmq ADD SEQUENCE pgmq.q_<your_queue_name>_msg_id_seq

Yes, I confirm this also works, thank you.

**Comment by elvizlai** [comment]
> > ALTER EXTENSION pgmq ADD SEQUENCE pgmq.q_<your_queue_name>_msg_id_seq
> 
> Yes, I confirm this also works, thank you.

**CAUTION**, this blocks extension upgrade to 1.5.0, need to delete it before upgrade.
```
alter extension pgmq update;
ERROR:  sequence q_xxxx_msg_id_seq is already a member of extension "pgmq"
CONTEXT:  SQL statement "
            ALTER EXTENSION pgmq ADD SEQUENCE pgmq.q_xxxx_msg_id_seq
            "
PL/pgSQL function inline_code_block line 26 at EXECUTE
```
